name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-rpi-php-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-cli
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-cli
          build-args: |
            WITH_XDEBUG=1
            WITH_SQL_SRV=1
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-cli:latest
            ghcr.io/${{ github.repository }}/rp-php-cli:7.4
  build-rpi-php-cli-m1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-cli
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-cli
          platforms: linux/arm64
          build-args: |
             WITH_XDEBUG=1
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-cli:latest
            ghcr.io/${{ github.repository }}/rp-php-cli:7.4
  build-rp-fpm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-fpm
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-fpm
          platforms: linux/amd64
          build-args: |
            WITH_XDEBUG=1
            WITH_SQL_SRV=1
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-fpm:latest
            ghcr.io/${{ github.repository }}/rp-php-fpm:7.4
  build-rp-fpm-m1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-fpm
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-fpm
          platforms: linux/arm64
          build-args: |
            WITH_XDEBUG=1
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-fpm:latest
            ghcr.io/${{ github.repository }}/rp-php-fpm:7.4