name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-rpi-php-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-cli
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-cli
          #platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-cli:latest
            ghcr.io/${{ github.repository }}/rp-php-cli:7.4
  build-rpi-fpm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-fpm
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-fpm
          #platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-fpm:latest
            ghcr.io/${{ github.repository }}/rp-php-fpm:7.4
  build-rp-php-deployer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push rp-php-deployer
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-php-deployer
          #platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/rp-php-deployer:latest
  build-exim-relay:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push exim-relay
        uses: docker/build-push-action@v2
        with:
          push: true
          target: rp-exim-relay
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/rp-exim-relay:latest